Implementing basic FeedCategory model and tests
jchristi/syndicat pull request #7
Opened 2017-03-20 16:22 UTC by ZacheryPD

This history (and diff) is much cleaner now.  I have a hunch of what happened to the last one, so I'll avoid that moving forward.

2017-03-20 21:15 UTC, jchristi commented on models/index.js
> +  models.FeedCategory.belongsTo(models.User, { foreignKey: 'owner_uid' });
Missing association for ParentCategory (parent_cat)

2017-03-20 21:20 UTC, jchristi commented
Add association for parent category and a relevant test case(s)

2017-03-21 21:44 UTC, ZacheryPD commented
I went ahead and implemented the missing association, good catch!  Will this work, or do we also need an association to represent the other side of the relationship?  It looks like Sequelize can do both but I'm not familiar enough to say if we want to do that or not.

2017-03-21 21:50 UTC, jchristi commented
Whereas a category can only have one parent, a category can have many children. I think both associations should be defined.

2017-03-22 17:17 UTC, ZacheryPD commented
@jchristi this should be resolved now.  Make sure you take a look at the names of the associations, did I do that right?  I think I did, but I expected that syntax to be different...

2017-03-22 18:09 UTC, jchristi requested changes
minor text changes

2017-03-22 18:09 UTC, jchristi commented on tests/models/FeedCategory_test.js
> +    it('has a FedCategory (parent) property', co.wrap(function* (){
keep the test title simple: `has Parent property`

2017-03-22 18:09 UTC, jchristi commented on tests/models/FeedCategory_test.js
> +    it('has a FedCategory (children) property', co.wrap(function* (){
`has Children property`

2017-03-22 18:11 UTC, jchristi commented
@ZacheryPD the association names can be whatever we want. I'm debating whether they should be all lowercased or not.

2017-03-22 20:51 UTC, jchristi approved these changes

2017-03-22 20:52 UTC, merged