Feeds Tests.
jchristi/syndicat pull request #8
Opened 2017-03-21 19:48 UTC by RickKwok

All passed tests. Fixed issues.

2017-03-22 14:45 UTC, jchristi commented
Merge conflicts. Wait until Zach's PR (#7) for FeedCategory is merged before resolving.

2017-03-22 20:53 UTC, jchristi commented
Just merged #7, go ahead and rebase or re-merge your branch and re-submit.

2017-04-04 16:01 UTC, RickKwok commented
Hi @jchristi Jeremy, I have just removed all the conflicts. Would you check at your convenience please?

2017-04-06 01:11 UTC, jchristi requested changes
There are a number of ESLint errors, see the [Travis log](https://travis-ci.org/jchristi/syndicat/jobs/218520777) for details. You can run a lint locally with the `make lint` command.

2017-04-06 01:11 UTC, jchristi commented on models/FeedCategory.js
> +      }
We got rid of this method, it may have been the cause of performance issues in the old branch. Associations are performed in `models/index.js` now.

2017-04-06 01:11 UTC, jchristi commented on tests/models/Feed_test.js
> +global.getTestDB = co.wrap(function* () {
This function has been moved to `tests/index.js` so every model test can make use of it.

2017-10-06 14:13 UTC, closed without merging