Added Entry model and tests
jchristi/syndicat pull request #9
Opened 2017-03-22 02:29 UTC by nephdog

2017-03-22 14:18 UTC, jchristi requested changes
~~Add tests to feed and entry to test the association between the two~~
Nevermind, I was mistaken...that should be done with `UserEntry` model (see https://github.com/jchristi/syndicat/blob/slow/doc/ttrss.mysql.sql#L373)

2017-03-22 14:18 UTC, jchristi commented on models/index.js
>    models.AccessKey.belongsTo(models.User, { foreignKey: 'owner_uid' });
Need to add the association between a feed and feed entries:
'''Javascript
        Feed.hasMany(models.Entry, { foreignKey: 'feed_id' });
'''

2017-03-22 14:18 UTC, jchristi commented on tests/models/Entry_test.js
> +    yield Entry.sync({force: true});
A sync is already done when calling grtTestDB(). Why is it needed again here?

2017-03-22 14:18 UTC, jchristi commented on tests/models/Entry_test.js
> +let GetEntry = () =>  {
Function names should be camelCased for consistency. "Classes" (technically Prototypes in JS) are what should be TitleCased.

2017-03-22 14:18 UTC, jchristi commented on tests/models/Entry_test.js
> +    yield Entry.create(insert).then(function(response) {
One of the neat things about generators with async functions is that you can wrap them in a normal try/catch block. No "then/catch" calls necessary! Much cleaner.

2017-03-22 14:18 UTC, jchristi commented on models/Entry.js
> +    }
Missing feed_id foreign key

2017-03-22 14:18 UTC, jchristi commented on models/index.js
>    models.AccessKey.belongsTo(models.User, { foreignKey: 'owner_uid' });
And Entry belongs to feed

2017-03-22 14:36 UTC, jchristi commented on models/Entry.js
> +    }
Looking at the old code, it seems like I'm mistaken...there is a UserEntry model....ttrss code confuses me too :)

2017-04-01 02:55 UTC, nephdog commented on tests/models/Entry_test.js
> +    yield Entry.sync({force: true});
I was under the impression that this would clear the table at the start of every test.

2017-04-01 03:21 UTC, nephdog commented on tests/models/Entry_test.js
> +    yield Entry.create(insert).then(function(response) {
I can't seem to get the try catch worker properly without the promises. Is there an example you could point me to?

2017-04-04 21:21 UTC, jchristi commented
Sorry I haven't had the chance to review this yet, I will try to look at it tonight or tomorrow.

2017-04-06 01:18 UTC, jchristi commented on tests/models/Entry_test.js
> +    yield Entry.sync({force: true});
The format used for all the other tests except this and the one below is the proper one:
```javascript
let sequelize = yield getTestDB();
```
The `getTestDB()` function creates a new SQLite database in memory every time it is called.

2017-04-06 02:02 UTC, jchristi commented on tests/models/Entry_test.js
> +    yield Entry.create(insert).then(function(response) {
From the author of the `co` library: https://medium.com/@tjholowaychuk/callbacks-vs-coroutines-174f1fe66127#3f51

No worries if you can't get it working though. It's concise either way, just figured I'd mention it as its a nice thing about async generators.

2017-04-06 02:06 UTC, jchristi commented
GitHub seems to have swallowed our conversation about async generators and try/catch blocks. Here is an example from the author of the `co` library: https://medium.com/@tjholowaychuk/callbacks-vs-coroutines-174f1fe66127#3f51. No worries about the use of promises though, it is the same number of lines so not a big deal.

2017-10-06 14:13 UTC, closed without merging